import argparse
import logging
import time

def check_generator(p, g):
    order = p-1
    logging.debug("order: {}".format(order))

    tmp = g
    exp = 1
    logging.debug("g: {}, exp: {}, tmp: {}".format(g, exp, tmp))

    while tmp != 1:
        tmp *= g
        tmp %= p
        exp += 1
        logging.debug("g: {}, exp: {}, tmp: {}".format(g, exp, tmp))
        if exp % 10000000 == 0:
            logging.info("p: {}, g: {}, exp: {}, tmp: {}".format(p, g, exp, tmp))

    return order == exp

def evaluate_g_x(p, g, x):
    y = -1
    start = time.time()

    y = (g ** x) % p

    end = time.time()
    et = end - start
    return y, et

def find_discrete_log(p, y, g):
    tmp = 1
    start = time.time()

    for i in range(1, p):
        tmp *= g
        tmp %= p
        if y == tmp:
            x = i 

    end = time.time()
    et = end - start
    return x, et

def command_line_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-g", metavar="<generator>", help="Generator", type=int, required=True)
    parser.add_argument("-x", metavar="<number x>", help="Number x", type=int, required=True)
    parser.add_argument("-y", metavar="<number y>", help="Number y", type=int, required=True)
    parser.add_argument("-l", "--log", metavar="<log level (DEBUG/INFO/WARNING/ERROR/CRITICAL)>", help="Log level (DEBUG/INFO/WARNING/ERROR/CRITICAL)", type=str, default="INFO")
    args = parser.parse_args()
    return args

def main():
    args = command_line_args()
    log_level = args.log
    logging.basicConfig(level=log_level)

    p = 2147483647
    g = args.g
    x = args.x
    y = args.y

    logging.info("The prime number {} is automatically selected".format(p))
    logging.info("You entered {} for the generator".format(g))

    if check_generator(p, g):
        logging.info("The number {} is a valid generator in the group generated by the prime number {}".format(g, p))
        y, et = evaluate_g_x(p, g, x)
        logging.info("y = {} from p = {}, g = {}, and x = {}".format(y, p, g, x))
        logging.info("The elapsed time required to find y given g and x is {}".format(et))

        x, et = find_discrete_log(p, y, g)
        logging.info("x = {} from p = {}, y = {}, and g = {}".format(x, p, y, g))
        logging.info("The elapsed time required to find x given y and g is {}".format(et))
    else:
        logging.error("The number {} is not a valid generator in the group generated by the prime number {}".format(g, p))
    
if __name__ == "__main__":
    main()
